### ISSUE TITLE
Styles for all WYSIWYG options

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#100]

**Comment by msayoung** [comment]
Having reviewed what's there, we just need to add the contrasting colour for the primary call out style. 

For list items, there is a style called "green ticks" which doesn't do anything at present. Do we want it? Should we bother?

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites_base/pull/101

**Comment by msayoung** [comment]
@markconroy do you have any thoughts about whether we should bother with a style for the list style "Green ticks" ? 



![Image](https://user-images.githubusercontent.com/3852805/189347900-c1480a2f-ba55-4b5e-b731-82a936d8b306.png)

As it's there I guess it should go something? 

There are also link styles for "PDF link" which looks the same as a normal link. Should we update that too? 

If so I think these should both be in localgov_base

**Comment by markconroy** [comment]
#101 is merged, so I think this can be closed?

**Comment by msayoung** [comment]
One more: https://github.com/localgovdrupal/localgov_base/pull/280
