### ISSUE TITLE
Layout options: slightly wider doesn't work.

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#117]
When you pick a page section, and choose the width, the "slightly wider than content area" option doesn't have an effect. 
@markconroy thoughts?

**Comment by markconroy** [comment]
Thoughts? Yes, I thought it worked. 😆 

Should be a fairly easy fix.

**Comment by markconroy** [comment]
This will be fixed when we get this merged and released: https://github.com/localgovdrupal/localgov_base/pull/288
