### ISSUE TITLE
Error: viewing blog channel when "Advanced > Teaser image style" is set

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#120]
The website encountered an unexpected error. Please try again later.
Error: Call to a member function getValue() on null in localgov_microsites_base_preprocess_node() (line 489 of themes/contrib/localgov_microsites_base/localgov_microsites_base.theme).
localgov_microsites_base_preprocess_node(Array, 'node', Array)

**Comment by msayoung** [comment]
@markconroy - this won't be a thing when stephen's MR is merged

**Comment by markconroy** [comment]
👍

**Comment by msayoung** [comment]
This is fixed now
