### ISSUE TITLE
News filter blocks - design

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#141]
Using the accent-2 results in garish results, particularly if heading 2 has a colour set. I've gone for something subtler by default

- - https://github.com/localgovdrupal/localgov_microsites_base/pull/139

**Comment by msayoung** [comment]
![Image](https://user-images.githubusercontent.com/3852805/196935519-90aa51b6-47b2-4443-8d81-21c8c9c9568d.png)

**Comment by markconroy** [comment]
Can we close this?
