### ISSUE TITLE
Display bug: Promoted IA block

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#151]
![Image](https://user-images.githubusercontent.com/3852805/197555465-2a94db00-8315-4f5d-8579-475e1b6ac46e.png)

Headings and links not picking up alt colour

**Comment by msayoung** [comment]
I think this was working so may be the fallout of moving css around

**Comment by markconroy** [comment]
Did you clear the cache?

**Comment by msayoung** [comment]
i did.

**Comment by markconroy** [comment]
I'm out of ideas.

**Comment by msayoung** [comment]
that's ok, i'll have a look. I have an idea

**Comment by markconroy** [comment]
Seems okay to me. Deliberatly choosing ugly colours to make sure.

![Screenshot 2022-10-24 at 16 00 06](https://user-images.githubusercontent.com/2183332/197558804-c4f01e7f-0fc6-415a-bd4d-99cd4bb67271.jpg)

**Comment by msayoung** [comment]
try : no background colour on the section, and a dark secondary colour

**Comment by markconroy** [comment]
```--color-page-section-background-color-1-link-color: var(--color-page-section-background-color-1-link-color);```

Looks like we have a variable set to itself. Maybe that's giving us a cock up?

**Comment by markconroy** [comment]
That's kind of a "works as designed" item, which is a bit crap. The backgrounds chosen for the section don't have any knowledge that the paragraphs in the sections might have a background colour.

In this case, if we choose "light gray" for the background, then the featured ia-block says "hey, that's light grey, let's contrast that with black", but then the page section says "oooh, we're light grey, I bet black for text and links would be very oh la la".

I think we'll need some more varialbes for this class:

```
.page-section-background-color-3 .ia-block--featured {
  background-color: var(--some-new-varialbe);
  color: var(--some-other-new-variable)
}

.page-section-background-color-3 .ia-block--featured a {
  color: var(--some-other-new-variable-as-well)
}
```

And might want to repeat that for background colour 1 and 2 for page layout.
