### ISSUE TITLE
Display bug: sidebar facets

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#154]
can't read the sidebar facets 

![Image](https://user-images.githubusercontent.com/3852805/197556369-31ea27c8-a891-4ccc-a0e7-f8b0cc93d4d7.png)

**Comment by markconroy** [comment]
What did you do to see this result? On a fresh install, we can easily see the facets.

![Screenshot 2022-10-25 at 09 23 35](https://user-images.githubusercontent.com/2183332/197722575-0e165487-71de-4689-a4c0-e4fd08c116f1.jpg)
