### ISSUE TITLE
Submenu icons not aligned  

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#164]
the default chevron icon is not aligned , which is particularly obvious when we set a small menu font size

![image](https://user-images.githubusercontent.com/3852805/197585036-0957e5c1-43a6-4cf8-a616-ce3d7331cc22.png)

**Comment by markconroy** [comment]
I bet there's too much padding on the icon container. We could try set the padding on that to be the same as the font size of the main menu, that might kick it into shape.

**Comment by msayoung** [comment]
Sonia's taking a look at this one

**Comment by finnlewis** [comment]
See https://github.com/localgovdrupal/localgov_microsites_base/pull/166
