### ISSUE TITLE
Related news appears before layout content

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#172]
![Image](https://user-images.githubusercontent.com/3852805/203550064-df0a395c-d430-494d-80e2-ac1f160520e6.png)

**Comment by msayoung** [comment]
I think we want the Related news to appear after the other content.

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites_group/pull/343

**Comment by markconroy** [comment]
I'm guessing this is fixed after https://github.com/localgovdrupal/localgov_microsites_group/pull/343
