### ISSUE TITLE
Microsite 1 admin - set default colours and theme configuration for site 1

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_base#2]
## User story

As a microsite 1 admin

I want to add default colours to site 1

So that I don't need to set colours for each config option

## Notes

Questions: 

- [ ] What are the names of the groupings?
- [ ] What does it look like? 
- [ ] Are there examples of this elsewhere? 
- [ ] Do we want a restricted palette? 
- [ ] Do we want a colour picker?

**Comment by msayoung** [comment]
https://miro.com/app/board/uXjVO9o1iRk=/?moveToWidget=3458764524141686576&cot=14
