### ISSUE TITLE
Removing bread crumbs from the home page

### ISSUE THREAD

**Issue by tom-watson-croydon** [localgovdrupal/localgov_microsites_base#207]
I am wanting to remove the breadcrumbs from the home page as there is no path yet created thus leaving 'Home' as the only breadcrumb.

It has been recommended that this is created as a check box.

**Comment by finnlewis** [comment]
Thanks for raising this in Slack and here @tom-watson-croydon! It's an obvious thing that people might want to have control over. 

From the Slack discussion, it sounds like @markconroy has a plan to add a checkbox. 

CC @willguv for product owner / team awareness.

**Comment by tom-watson-croydon** [comment]
Hi @finnlewis  @markconroy! Was just wondering if there was any update on this ticket?

**Comment by markconroy** [comment]
Hi @tom-watson-croydon 

I've started some work on this. There's 2 PRs linked to above. Once we have those merged, you'll be in business.

**Comment by tom-watson-croydon** [comment]
Thanks @markconroy !!

**Comment by willguv** [comment]
@tom-watson-croydon thanks for raising this - I think it's done, so closing this issue

See https://github.com/localgovdrupal/localgov_microsites_base/pull/214
