### ISSUE TITLE
Footer columns are not responsive on small screen

### ISSUE THREAD

**Issue by bobbulman** [localgovdrupal/localgov_microsites_base#220]
When viewing a site with three footer columns on a small screen device/smartphone they do not stack but just get very narrow 
![image](https://github.com/localgovdrupal/localgov_microsites_base/assets/67878800/aca242b7-1007-4326-b730-b2cef2492c1f)

**Comment by markconroy** [comment]
Thanks @bobbulman 

I have #221 created to fix this if you want to test it?

**Comment by bobbulman** [comment]
Hi @markconroy  just wanted to say thanks for fixing this - sorry I took so long to get back to you (on annual leave)
