### ISSUE TITLE
Page top section layout

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#23]
- [x] Reorder field/blocks as per wireframe
- [x] Style the standfirrst a bit bigger

![Image](https://user-images.githubusercontent.com/3852805/169876140-f9224993-0f0c-4765-880c-d00f8aa4b9ac.png)

**Comment by msayoung** [comment]
@markconroy did you have a thought about how to print the page fields as above. 

I see we have banner, and content_top regions. how would you prefer to get the fields in there. 

(and do we want to use them, as I'm going to suggest they all come in to the `<main>` tag )

**Comment by markconroy** [comment]
Something simple like a field_group might work, where we can add any field from any content type into it, and just render them as a flat list of fields.

Or we could create a view mode and render that via views or something to place them there.

For sure, we need to get it all inside the `<main>` tag. 

Let's start chatting about this once we have the user testing started.

**Comment by finnlewis** [comment]
It would be good to get this in place before testing if possible.

What are the tasks to do? 

Templates? Themeing?
