### ISSUE TITLE
dpm() output doesn't print in microsite base theme

### ISSUE THREAD

**Issue by anthonylindsay** [localgovdrupal/localgov_microsites_base#242]
To reproduce:

1. install devel
2. stick a dpm() in a form_alter, a views_prerender, or a block plugin, for example.
3. reload to trigger it
4. see nothing.
5. load an admin page and see your dpm() output.

**Comment by markconroy** [comment]
It looks like

```
{% if has_messages %}
  {{ page.messages }}
{% endif %}
```

in `page.html.twig` is returning false all the time.
