### ISSUE TITLE
The "domain_group_resolver" service is deprecated. You should use the group sites context directly instead.      

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_base#257]
See: https://github.com/localgovdrupal/localgov_microsites_project/actions/runs/8740878820/job/24001970866?pr=46#step:4:47

The "domain_group_resolver" service is deprecated. You should use the   
         group sites context directly instead.

**Comment by markconroy** [comment]
I think this has been fixed as we are now using `localgov_microsites_group_get_by_context()`
