### ISSUE TITLE
Event nodes missing breadcrumb

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_base#275]
Event nodes don't seem to have breadcrumbs.

I think we're missing a template for the full event node. 

![image](https://github.com/user-attachments/assets/50b62fda-5452-4bee-924d-4a8945749d3b)

**Comment by markconroy** [comment]
Fixed via #276 

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
