### ISSUE TITLE
Events don't have an h1 

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#285]
I think this is a microsite only problem, but it may be config and not in the theme. 

Events don't have an H1 on the page. Not sure when this happened, but I'm fairly certain it used to. 

eg: https://site3.demo.microsites.localgovdrupal.org/events/park-run 

![image](https://github.com/user-attachments/assets/39662b4c-d690-4364-852a-e70cb2c5000a)

**Comment by markconroy** [comment]
Looks like when we (@finnlewis is to blame 😆 ) added the custom template for events from localgov_base to here, we (again @finnlewis 😆 ) didn't add the `{{ label }}` to it. So when it stopped using the node--full.html.twig from this repo, the title was gone.

#288 Should fix it.
