### ISSUE TITLE
Heading font weight bold not applying

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_base#45]
Tested with Open Sans (in the Golbal Styles)

**Comment by finnlewis** [comment]
@msayoung wanted to discuss with @markconroy

**Comment by finnlewis** [comment]
Bump?

**Comment by finnlewis** [comment]
Bump?

**Comment by markconroy** [comment]
@msayoung Can you confirm this is fixed now with this commit: https://github.com/localgovdrupal/localgov_microsites_group/commit/e719428bd835eb04d720e5e2565a064af36f69b7

Sorry, I thought I was on a branch but pushed directly to the 1.x branch. Note, the commit is against the `localgov_microsites_group` module.

**Comment by msayoung** [comment]
done, thanks!
