### ISSUE TITLE
Frontend: Header & footer design tweaks

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_base#47]
@richard-s-rowley any direction here? 

If not @msayoung might go ahead with something...

**Comment by msayoung** [comment]
I did some things. (I've just set the width and the colours through the UI) 

![Image](https://user-images.githubusercontent.com/3852805/176471010-3684a376-4d95-431f-8cde-53596edf2ba1.png)

![Image](https://user-images.githubusercontent.com/3852805/176471413-f8ad2993-5956-45b2-9864-37bfd700827d.png)

**Comment by msayoung** [comment]
Here it is with no colours



![Image](https://user-images.githubusercontent.com/3852805/176471956-fee29ee0-1682-41d6-a601-bacd8ea42fe4.png)

**Comment by msayoung** [comment]
I've set it up with the assumption that people will be able to override:

- Site name size
- Site name font weight
- Main menu size
- Main menu font weight
- Utitlity menu site
- Utility menu font weight
- vertical alignment of header items
- footer grid spacing (gap between columns)
- footer grid horizontal alignment (space-between, center etc)

However we'll need to add those fields to the UI if we want this.

**Comment by msayoung** [comment]
https://github.com/localgovdrupal/localgov_microsites_base/pull/60

**Comment by markconroy** [comment]
This looks brilliant @msayoung. Well done. Our system is starting to take shape.

**Comment by msayoung** [comment]
Currently we can change

- footer text colour
- footer link / hover
- header text colour
- header link / hover colour 
- site name size / weight
- site slogan size / weight
- main menu size / weight

On the functional requirements @finnlewis it says that we need to change the colour, font, and size of the footer and header text. 

Do we think this is true? And if so do we need to change all of the following separately?

- site name colour
- site name font
- site slogan colour
- site slogan font
- main menu font
- main menu link / hover colour 
- utility menu font
- utility menu link / hover colour

@richard-s-rowley do you have thoughts ?

**Comment by richard-s-rowley** [comment]
thanks @msayoung 

Let's leave it with what we already have for now. Those choices give the admin a lot of control over the appearance without being overwhelming or possibly creating a mixed-up site.

Something to test though.

**Comment by msayoung** [comment]
great, in which case I am closing this
