### ISSUE TITLE
Style second and third level dropdown menus

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#69]

**Comment by finnlewis** [comment]
@markconroy not sure if it is too late to be of use, but we've generally defaulted to using Tanc's responsive menu module where multi-level menus are needed at desktop and mobile: https://www.drupal.org/project/responsive_menu

I didn't realise you weren't aware of it.

**Comment by markconroy** [comment]
Thanks @finnlewis 

That looks really interesting, but not sure it's right for our use case. We have an "off canvas" region that can have _anything_ in it - menu, search, etc for small screens, not just a mobile menu. 

Also, I'm trying to stay away from things that:
1. Load external libraries, so our theme can be as easy to use as possible, and
2. Does not use jQuery
