### ISSUE TITLE
Dropdown menu improvements

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#76]
Suggested improvements

## Config

- [ ] Have the main menu items expanded by default ( Question ? )
- [x] The utility menu should be in the off-canvas region by default (title hidden) (https://github.com/localgovdrupal/localgov_microsites_base/issues/81)

## Styles

- [x] - expand submenu on hover as well as click (discuss) - Maria to look into changing aria attributes on hover.
- [ ] - minimise layout shift

## Overriding styles

- [x] - background colour of submenus?
- [x] - icon for button? 
- [x] - font colour / size for dropdown menus
- [x] - icon for mobile menu?
- [x] - mobile menu flyouy bg colour
- [x] - mobile menu text styles? 

## Accessibility (todo)

- [x] - check button size (touch target size)
- [x] - check with screen reader ( aria-labels)
- [x] - close sub-menu with ESC ? where should focus go? 
- [x] - should _not_ be able to tab out of the mobile submenu without closing.

**Comment by msayoung** [comment]
Most of the other things I need to talk to @markconroy about. 

@markconroy also remind me to ask you about the icon.twig.html and how we are using it in localgov_microsites_base

**Comment by markconroy** [comment]
> Most of the other things I need to talk to @markconroy about.

I'm looking forward to a chat ;)

> @markconroy also remind me to ask you about the icon.twig.html and how we are using it in localgov_microsites_base

There should be inline documentation about how this works. Not sure if it's being used yet in localgov_microsites_base

**Comment by markconroy** [comment]
1. Expand by default - this doesn't seem possible via the UI when using group_content_menu
2. Layout shift - I'm not sure there's more we can do with this

Shall we close this?
