### ISSUE TITLE
Place utility menu in off canvas region by default

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_microsites_base#81]

**Comment by markconroy** [comment]
This seems to already be in place. (https://github.com/localgovdrupal/localgov_microsites_base/blob/1.x/config/install/block.block.localgov_microsites_base_off_canvas_utility_menu.yml)

**Comment by msayoung** [comment]
This looks like it should work but it doesn't. @stephen-cox could you take a look

**Comment by stephen-cox** [comment]
That config places the utility menu in the `utility_menu` region: https://github.com/localgovdrupal/localgov_microsites_base/blob/3ed0dc0e87fba7710978b5fdf2c82138bd1fdaa3/config/install/block.block.localgov_microsites_base_off_canvas_utility_menu.yml#L13

PR #102 Sorts out the naming of things and includes new config so the utility menu is in the utility menu and off canvas regions.
