### ISSUE TITLE
Events theming and customisation

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_base#82]
Give the event nodes and events listing /events a style / theme review.

Decide is any further custom / overrides are needed. 

Early wireframes
https://miro.com/app/board/uXjVO9o1iRk=/?moveToWidget=3458764523794796901&cot=14 

## Acceptance: 

1. Events look nice and accessible.
2. We have separate issues for custom overrides if needed.

**Comment by msayoung** [comment]
![Image](https://user-images.githubusercontent.com/3852805/179971895-9fa8e4ff-d3ea-4114-a10c-b787f93bef9f.png)

**Comment by markconroy** [comment]
I _think_ this is themed by https://github.com/localgovdrupal/localgov_microsites_base/pull/86
