### ISSUE TITLE
News theming and customisation

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_base#83]
Give the news nodes and news channel / listing a style / theme review.

Decide is any further custom / overrides are needed. 

Early wireframes
https://miro.com/app/board/uXjVO9o1iRk=/?moveToWidget=3458764523794796901&cot=14 

## Acceptance: 

1. News looks nice and accessible.
2. We have separate issues for custom overrides if needed.

**Comment by msayoung** [comment]
![Image](https://user-images.githubusercontent.com/3852805/179972152-0c4d1169-ed9c-494f-a678-2ca53de7447f.png)

**Comment by msayoung** [comment]
We have a banner image on the wireframe for news. 

Should we use the current news image field (currently generates the teaser image) or add the banner paragraph ? 

Thoughts @markconroy ?

**Comment by msayoung** [comment]
We also have a banner image on the Newsroom wireframe. 

We have no image field on the newsroom. I think the banner paragraph makes sense in this case

**Comment by markconroy** [comment]
I think we'll use the banner paragraph for both of these content type - nice for ensuring consistency.
