### ISSUE TITLE
News updates

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_microsites_base#89]
- [x] update spacing between related news items
- [x] add 'Related news' heading
- [x] put container classes on the newsroom page so they are not 100% width of screen
- [ ] (something to) let users know they are searching inside news when they use the news search block in the newsroom sidebar

**Comment by markconroy** [comment]
> (something to) let users know they are searching inside news when they use the news search block in the newsroom sidebar

Let's create an issue for localgov_news core to set that block label to 'Search news' instead of 'Search'

**Comment by msayoung** [comment]
@markconroy - can you also add the Newsroom page title to the Newsroom display ?

**Comment by markconroy** [comment]
@msayoung it should be there already - https://github.com/localgovdrupal/localgov_microsites_base/pull/91/files#diff-17ca2f059f02d539fef73634fb5c6ce27deb890e3f49560907a76dd0a27564e6R101

**Comment by msayoung** [comment]
It is, thanks!
