### ISSUE TITLE
Bug: menu items dont appear on a white header

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#96]

**Comment by markconroy** [comment]
I think this is working fine. If you choose a white background, the links are not visible because our default links are set to white, but they are certainly there.

Editors will need to assign a colour to the links for them to show up.

**Comment by msayoung** [comment]
True - I wonder if we should put the paired fields in fieldsets to make it clearer they should be set together?

**Comment by markconroy** [comment]
That might be a good idea. Maybe we should create a follow up and see if we have enough budget for it when we get other necessary items cleared first.

**Comment by msayoung** [comment]
Done: https://github.com/localgovdrupal/localgov_microsites_group/issues/246

Closing this
