### ISSUE TITLE
Documentation for localgov_microsites_base

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_base#97]

**Comment by msayoung** [comment]
Readme started https://github.com/localgovdrupal/localgov_microsites_base/pull/98 

We should add some more examples of things to change.

**Comment by markconroy** [comment]
We also need to mention in the readme, that you 1. enable your theme, and 2. set it as default. You can't use the "enable and set as default" option in one fell swoop. This is important to keep the blocks in position.

**Comment by markconroy** [comment]
I've added this comment to the README and merged it to 1.x. Shall we close this issue?
